// <auto-generated />
using System;
using Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Application.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210328175507_AddedDefaultValues")]
    partial class AddedDefaultValues
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Application.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Confirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("confirmed")
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("CountryRegion")
                        .HasColumnName("country_region")
                        .HasColumnType("varchar")
                        .HasMaxLength(256);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created_at")
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'utc'");

                    b.Property<int>("Deaths")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("deaths")
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("ObservationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("observation_date")
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'utc'");

                    b.Property<string>("ProvinceState")
                        .HasColumnName("province_state")
                        .HasColumnType("varchar")
                        .HasMaxLength(256);

                    b.Property<int>("Recovered")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("recovered")
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("updated_at")
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'utc'");

                    b.HasKey("Id");

                    b.ToTable("covid_observations");
                });
#pragma warning restore 612, 618
        }
    }
}
